### PR TITLE
port ColorfulClouds API

### PR DESCRIPTION
**Pull request by shindgewongxj**
https://github.com/WordlessEcho/iRingo/blob/3cb36be332d134542ff4e229bccc94e825691d94/js/Apple_Weather.js#L315

Added Language Detection.

THANKS to WordlessEcho!

### CODE REVIEW

**Comment by shindgewongxj** [comment]
https://github.com/WordlessEcho/iRingo/blob/3cb36be332d134542ff4e229bccc94e825691d94/js/Apple_Weather.js#L315

**Comment by VirgilClyne** [comment]
@WordlessEcho 直接并到main上吗？怕怕

**Comment by WordlessEcho** [comment]
> @WordlessEcho 直接并到main上吗？怕怕

尴尬了，忘记叫他改分支到beta了

**Comment by WordlessEcho** [comment]
Thank you!

**Pull request merged**
